import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import Header from 'Components/header';
import Footer from 'Components/footer';


const Home: NextPage = () => (
  <div>
    <Head>
      <title>Welcome to Awesome!</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />

    <div>
      <h1>
        Content
      </h1>
    </div>

    <Footer />
  </div>
);

export default Home;
